### ISSUE TITLE
Add layouts to item_content_card_list

### ISSUE THREAD

**Issue by norbertlaposa** [laposa/onyx#63]
In file bo/node/item_content_card_list.html

**Comment by Kuchtin** [comment]
new tasks:

- [ ] delete add button on pods, add one at the end of the list
- [ ] remove pages from node list
- [ ] add headings - Page list / Content list
- [ ] change buttons - labels to add page & add content 
- [ ] new list - page list with only pages and button add list 
- [ ] leave current node list under advanced with button add node that allows adding any type of node
