### ISSUE TITLE
Implement deep links for pages

### ISSUE THREAD

**Issue by hugo187** [laposa/onyx#78]
We should allow editors to link any website page with a deep link. Facebook has developed meta tags for this, which seem be to suitable for this: https://developers.facebook.com/docs/applinks/metadata-reference

So for iOS we should have something like:

````html
    <meta property="al:ios:url" content="realrewards://home"/>
    <meta property="al:ios:app_name" content="SuperValu Real Rewards"/>
    <meta property="al:ios:app_store_id" content="1150433976"/>
````

For Android we should have something like:

````html
    <meta property="al:android:package" content="com.aimia.android.musgrave"/>
    <meta property="al:android:app_name" content="SuperValu Real Rewards"/>
    <meta property="al:android:url" content="realrewards://home"/>
````

The Onyx configuration should include the following parameters:

- List of supported mobile apps (ideally an array in one of `conf/*.php` files). Each app in the array should include:
  - App Name
  - URL Scheme (e.g. `realrewards://`))
  - App Store ID
  - Android Package
  - Regex to validate deeplink URLs

So, if the Onyx instance has one or more mobile app configured, then in Onyx backoffice, each page should include a Deep Link section with a text input and regex based validation. This should be saved into `custom_fields` column in the `common_node` table.

**Comment by norbertlaposa** [comment]
@hugo187 I would change "List of all deeplinks supported by the app." to "Regex of supported deeplinks by the app".
